name: Manual test

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: |
          echo "build running..."
          echo "Workflow File: $(echo $GITHUB_WORKFLOW_REF | cut -d'/' -f4 | cut -d'@' -f1)"
          echo $(basename $GITHUB_WORKFLOW_REF)
          echo $GITHUB_WORKFLOW_REF
          sleep 5
  deploy-stage:
    runs-on: ubuntu-latest
    environment: stage
    steps:
      - name: Print Timestamp
        run: |
          echo "Deploying in stage"
          sleep 10
          echo "This deployment ran at $(date)"
  deploy-prod:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Print Timestamp
        run: |
          echo "Deploying in Prod"
          sleep 10
          echo "This deployment ran at $(date)"
          
