name: Manual test

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: |
          echo "build s
          sleep 5
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Print Timestamp
        run: |
          echo "This workflow ran at $(date)"
          sleep 10
