name: Repository event dispatch test

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: |
          echo "build running..."
          sleep 5
  create-artifact-payload:
    runs-on: ubuntu-latest
    steps:
      - name: Print Timestamp
        run: |
          sleep 5
          echo "Calling the api"
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer ${{ secrets.REPO_DISPATCH_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{
              "event_type": "custom-event",
              "client_payload": {
                "message": "Triggered from GitHub Actions",
                "timestamp": "${TIMESTAMP}"
              }
            }' \
            https://api.github.com/repos/${{ github.repository }}/dispatches
          echo "Called the api"
        
